### ISSUE TITLE
Yet another systems language?

### ISSUE THREAD

**Issue by pyros2097** [orange-lang/orange#7]
How is this language better or [going to be better] than [crystal](https://github.com/manastech/crystal) or [pony](https://github.com/CausalityLtd/ponyc). To me it seems a lot like crystal. Any specific design goals that's gonna seem interesting?

**Comment by rfratto** [comment]
Originally, I was simply working on a language that had syntax similarly to a scripting language to achieve higher productivity than other systems language. The main goal is evolving now as I'm still trying to find where it fits in among the other languages, like the ones you mentioned. 

One of the current new goals is to make sure that Orange can be used to write bare metal applications like kernels and code for ARM development boards like the Arduino. Orange has pointer support, so you can get low level with your memory, and it will eventually support inline assembly for when you need fine-grain control over registers. 

I don't want low level to be the main focus though; I want a high level API that works the same across all major OSes. As for interesting/unique goals, I'm just not sure yet. Concurrency seems like a must, but I'm still thinking about this.

**Comment by pyros2097** [comment]
That would be really good then I wouldn't need to write kernel modules in C again and ditch embedded C for development boards. There is this guy who has done it for golang but I don't think it can access registers as such https://sites.google.com/site/embeddedgo/ and this one also https://github.com/SpaceLeap/go-embedded.

Are you planning on adding async support in the near future like node uses libuv and crystal uses libpcl in the standard library?

Are you also going to be bootstrapping the compiler. That would solve a lot of headache learning C++ to contribute?

And in the current version is it possible for me to write bindings for SDL, SFML and maybe even this [h2o](https://github.com/h2o/h2o) and make a usable application?

**Comment by rfratto** [comment]
With regards to asynchronous code, after looking more into Crystal and Pony, I have a few issues with their design: 

For Crystal, I don't like how typeless members become a union of types and restrict the calls you can do on them, forcing you to add generics. You can see this from their [documentation](http://crystal-lang.org/docs/syntax_and_semantics/generics.html). Orange shouldn't run into this issue since all classes who has members that aren't defined with types are generics by default. 

Another issue I have with Crystal and Pony are how they only allow you to accomplish certain tasks through using specialized syntax. For example, if you want a class to allocate on the stack and be passed by reference, you _have_ to use a Struct. There's no choice. If something is already a class and you want it to allocate on the stack, too bad. Pony has the same issue in another place: if you want a class to be asynchronous, you have to have it be an actor. 

In general, these things take away a lot of the freedom from developers, and I plan to avoid it with Orange. You can see the current idea for asynchronous code if you go to the Concurrency example on Orange's [website](http://orange-lang.org).

> Are you also going to be bootstrapping the compiler. That would solve a lot of headache learning C++ to contribute?

While the C++ I do use isn't necessarily as obtuse as other C++ code that's around, I'm not sure if I'm going to be bootstrapping Orange. It would require users to already have Orange to compile it (which causes a lot of headaches). 

> And in the current version is it possible for me to write bindings for SDL, SFML and maybe even this h2o and make a usable application?

No, not yet. Currently Orange can only build a file at a time, so it would be a huge pain to create a large application. Linking to libraries other than glibc currently isn't builtin, but that would be an easy extension. 

Currently, progress on the language is slower than it could be since I've been going back and solidifying its features. The things you want will be implemented with time, though.

**Comment by yorickdewid** [comment]
There seems to be an new demand for system level languages, C++ isn't what it should have been and there is space for alternatives. Go tries hard to fill that gap, but I think there is enough room for others too. The thing is that you need a specific selling point to distinguish Orange from the others like Crystal or ponyc. Right now the small footprint gives you some kudos :+1: although its not fully developed yet. I think techniques like concurrency, async (await), networking and such form 'de facto' for the future and should be supported anyway.

I'm looking for a C/C++ successor for a long time, and many have past since then. Somehow they always find a way to implement a feature and mess things up.  I don't like the Ruby / Crystal syntax as it looks more like a scripting languages than serious work. Pony is great but has some odd syntax declarations and very, very strange behavior on classes and objects that makes it more likely to be an toy languages above anything else. Go doesn't lack much on these points and seems to make some progression in popularity, but has some nasty downsides on binary compilation (I did a study on Golang a few weeks ago).

That fact that Crystal, Pony en Orange depend on the same backend doesn't automatically mean they kind of are the same thing (@pyros2097 I assume you implied that). LLVM must be seen as a pro rather than a con, and I expect the performance to improve significantly in the next few years. Languages like Orange can take the benefits of this and leave anything like a GCC far behind (that would be awesome, wouldn't it? :sunglasses: ) With a little luck you find yourself working on kernel level drivers written in complete Orange.

Just keep things simple in the core, aim for that C++ replacement spot and don't let your language be influenced by JavaScript (or any of the thousand clones). Mix that with a little C++ and Orange can really be 'the next thing'.

**Comment by rfratto** [comment]
I think it'll be easier to find a selling point for Orange once work on the standard library starts; since all the work is essentially core language features right now, it's hard to distinguish Orange from others while I'm essentially just playing catch up.

**Comment by BigBoneDaddy** [comment]
@pyros2097 Different system langs have different goods and different bads. Orange has so many goods! Other languages have so many bads! That is why Orange is important. It brings goods that others do not. I has not the bads that others have!

**Comment by rfratto** [comment]
I still don't have a answer for what Orange's selling point is, but I'm going to be closing this issue for now.
